#
#  Author: Hari Sekhon
#  Date: 2020-09-23 19:04:15 +0100 (Wed, 23 Sep 2020)
#
#  https://github.com/harisekhon/templates
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

# ============================================================================ #
#                         G C P   C l o u d   B u i l d
# ============================================================================ #

# Reference:
#
# https://cloud.google.com/cloud-build/docs/build-config

# gcloud builds submit --config cloudbuild-golang.yaml .

# tars $PWD to bucket called ${PROJECT_ID}_cloudbuild

# $PROJECT_ID is auto-populated by Cloud Build

steps:
# uses the official 'golang' docker image from DockerHub to build the binary
- name: golang
  args: ['go', 'build', '.']
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-go/bin/'
    # XXX: replace mybinary - should match the generated binary name (module basename in go.mod)
    paths: ['mybinary']
