#
#  Author: Hari Sekhon
#  Date: 2019-11-25 13:47:16 +0000 (Mon, 25 Nov 2019)
#
#  https://github.com/harisekhon/devops-perl-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME
  labels:
    app: APP
spec:
  # for persistent disks limited to 2 zones combined with GKE regional clusters
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - europe-west-1b
            - europe-west-1c
  selector:
    matchLabels:
      app: APP
      role: master
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: APP
        role: master
        tier: backend
    spec:
      progressDeadlineSeconds: 120
      containers:
      - name: master
        image: k8s.gcr.io/APP:latest
        ports:
          - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
        resources:
          requests:
            # millicores - 1/1000 of a CPU / vCPU
            # 100m = 1/10th of CPU core
            cpu: 100m
            # literal MiB
            memory: 100Mi
          volumes:
            - name: APP-vol
            # GKE will automatically create the underlying disk for us using default storage provider's dynamic provisioner
              claimName: APP-dynamic-pvc
              readOnly: true
          volumeMounts:
            - name: APP-vol
              mountPath: /mnt/APP-vol
