#
#  Author: Hari Sekhon
#  Date: 2020-02-13 12:54:31 +0000 (Thu, 13 Feb 2020)
#
#  https://github.com/harisekhon/devops-perl-tools
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn
#  and optionally send me feedback to help improve or steer this or other code I publish
#
#  https://www.linkedin.com/in/harisekhon
#

apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  # minAvailable: 4  # < 1.7 - must calculate yourself, eg 2/3, or 4/5
  maxUnavailable: 1  # 1.7+
  selector:
    matchLabels:
      app: zookeeper
